version: '3'

services:
  trino:
    build: .
    image: trinodb/trino:local
    volumes:
      - ./catalog:/etc/trino/catalog
    ports:
      - '8080:8080'
    networks:
      - dd_net
  doris-fe:
    image: "apache/doris:1.2.1-fe-x86_64"
    hostname: "fe"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
    ports:
      - 8030:8030
      - 9030:9030
    networks:
      dd_net:
        ipv4_address: 172.20.80.2
  doris-be:
    image: "apache/doris:1.2.1-be-x86_64"
    hostname: "be"
    depends_on:
      - doris-fe
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.3:9050
    ports:
      - 8040:8040
    networks:
      dd_net:
        ipv4_address: 172.20.80.3
networks:
  dd_net:
    ipam:
      config:
        - subnet: 172.20.80.0/16